name: cellPool_R
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_16
  - binutils_impl_linux-64=2.43
  - bioconductor-complexheatmap
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cairo
  - curl=8.10.1
  - expat=2.6.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-aarch64=15.1.0
  - gfortran_impl_linux-aarch64=15.1.0
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-aarch64=15.1.0
  - harfbuzz=9.0.0
  - icu=75.1
  - kernel-headers_linux-aarch64=5.14.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-aarch64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.10.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=15.1.0
  - libgcc-devel_linux-aarch64=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.80.3
  - libgomp=15.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.44
  - libsanitizer=15.1.0
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-aarch64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - make=4.4.1
  - ncurses=6.5
  - openssl=3.3.2
  - pandoc=3.4
  - pango=1.54.0
  - pcre2=10.44
  - pixman=0.43.2
  - pthread-stubs=0.4
  - r=4.4
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.5.1
  - r-base64enc=0.1_3
  - r-bit=4.5.0
  - r-bit64=4.5.2
  - r-blob=1.2.4
  - r-boot=1.3_31
  - r-broom=1.0.6
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-circlize=0.4.16
  - r-class=7.3_22
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-cluster=2.1.6
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-conflicted=1.2.0
  - r-cpp11=0.5.0
  - r-crayon=1.5.3
  - r-curl=5.2.1
  - r-data.table=1.15.4
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-dendextend=1.17.1
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.0
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreign=0.8_87
  - r-fs=1.6.4
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-getoptlong=1.0.5
  - r-ggplot2=3.5.1
  - r-globaloptions=0.1.2
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gridextra
  - r-gtable=0.3.5
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.9=r44h2b5f3a1_0
  - r-kernsmooth=2.23_24=r44hc2011d3_1
  - r-knitr=1.48=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_6=r44hb1dbf0f_1
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-lubridate=1.9.3=r44hdb488b9_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_60.0.1=r44hb1dbf0f_1
  - r-matrix=1.6_5=r44he966344_1
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_1=r44h0d28552_1
  - r-mime=0.12=r44hb1dbf0f_3
  - r-modelr=0.1.11=r44hc72bb7e_2
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_165=r44hbcb9c34_1
  - r-nnet=7.3_19=r44hb1dbf0f_2
  - r-openssl=2.2.2=r44he8289e2_0
  - r-patchwork=1.3.0=r44hc72bb7e_0
  - r-pillar=1.9.0=r44hc72bb7e_2
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-plyr=1.8.9=r44ha18555a_1
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-processx=3.8.4=r44hb1dbf0f_1
  - r-progress=1.2.3=r44hc72bb7e_1
  - r-ps=1.7.7=r44hdb488b9_0
  - r-purrr=1.0.2=r44hdb488b9_1
  - r-r6=2.5.1=r44hc72bb7e_3
  - r-ragg=1.3.3=r44h9aa3752_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.0.13=r44h0d4f4ea_0
  - r-readr=2.1.5=r44h0d4f4ea_1
  - r-readxl=1.4.3=r44he58e087_1
  - r-recommended=4.4=r44hd8ed1ab_1007
  - r-rematch=2.0.0=r44hc72bb7e_1
  - r-rematch2=2.1.2=r44hc72bb7e_4
  - r-reprex=2.1.1=r44hc72bb7e_1
  - r-rjson=0.2.23=r44h93ab643_0
  - r-rlang=1.1.4=r44ha18555a_1
  - r-rmarkdown=2.28=r44hc72bb7e_0
  - r-rpart=4.1.23=r44hb1dbf0f_1
  - r-rstudioapi=0.16.0=r44hc72bb7e_1
  - r-rvest=1.0.4=r44hc72bb7e_1
  - r-sass=0.4.9=r44ha18555a_1
  - r-scales=1.3.0=r44hc72bb7e_1
  - r-selectr=0.4_2=r44hc72bb7e_4
  - r-shape=1.4.6.1=r44ha770c72_1
  - r-spatial=7.3_17=r44hb1dbf0f_1
  - r-stringi=1.8.4=r44h33cde33_3
  - r-stringr=1.5.1=r44h785f33e_1
  - r-survival=3.7_0
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-textshaping=0.4.0
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.53
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5=r44h0d4f4ea_1
  - r-withr=3.0.1
  - r-xfun=0.47=r44h0d4f4ea_0
  - r-xml2=1.3.6=r44h8194278_2
  - r-yaml=2.3.10=r44hdb488b9_0
  - readline=8.2=h8228510_1
  - sed=4.8=he412f7d_0
  - sysroot_linux-64=2.17=h4a8ded7_16
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tzdata=2024a=h8827d51_1
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.3=hb9d3cd8_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.2.6=h166bdaf_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
prefix: /opt/conda/envs/cellPool_R
