name: cellPool_py3
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - munkres=1.1.4
  - networkx=2.7.1
  - numpy=1.22.3
  - pandas=1.4.2
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - matplotlib=3.7.2
  - pip=22.3.1
  - pip:
     - jax
     - jaxlib
     - basicpy==1.1.0
prefix: /
